# Generated by Django 4.2.7 on 2023-11-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.ImageField(default='default_banner.jpg', upload_to='event_banners/'),
        ),
    ]
